#!/bin/bash
# MoniHub Quick Start Commands

echo "🚀 MoniHub - Financial Literacy Hub for PNG Youth"
echo "=================================================="
echo ""
echo "📦 Installation:"
echo "  npm install"
echo ""
echo "🔥 Development:"
echo "  npm run dev"
echo "  Then open: http://localhost:5173"
echo ""
echo "📦 Production Build:"
echo "  npm run build"
echo "  npm run preview"
echo ""
echo "📁 Project Structure:"
echo "  src/components/  - Reusable UI components"
echo "  src/pages/       - Full page components"
echo "  src/App.jsx      - Main router"
echo "  src/index.css    - Global styles"
echo ""
echo "📄 Documentation:"
echo "  - README.md                    (Full overview)"
echo "  - README_NEW.md                (Detailed features)"
echo "  - SETUP.md                     (Development guide)"
echo "  - IMPLEMENTATION_CHECKLIST.md  (Feature list)"
echo ""
echo "🎨 Key Features:"
echo "  ✅ Home Page with Stori Vault (stories feed)"
echo "  ✅ Learning Modules (4 categories, 19 lessons)"
echo "  ✅ Goal Tracking & Kina Ledger"
echo "  ✅ Profile & Achievements (8 badges)"
echo "  ✅ Fixed Bottom Navigation (4 tabs)"
echo "  ✅ Deep-linkable Stories (/story/:storyId)"
echo "  ✅ Navy Blue & White Professional Design"
echo "  ✅ Mobile-First Responsive Layout"
echo ""
echo "🔗 Deep Linking Examples:"
echo "  /story/story-1  - From Street Sales to Shop Owner"
echo "  /story/story-2  - Building Wealth Through Savings"
echo "  /story/story-3  - First Investment Success"
echo "  /story/story-4  - Breaking Paycheck-to-Paycheck"
echo "  /story/story-5  - Entrepreneurship in Rural PNG"
echo ""
echo "🛠️ Tech Stack:"
echo "  - React 18"
echo "  - Vite"
echo "  - Tailwind CSS"
echo "  - React Router v6"
echo "  - Lucide React (icons)"
echo ""
echo "💡 Tips:"
echo "  - All mock data is in src/pages/ files"
echo "  - Update color palette in tailwind.config.js"
echo "  - Components are in src/components/"
echo "  - Customize stories in StoryPage.jsx"
echo ""
echo "Ready to build? Run: npm install && npm run dev"
echo ""
